# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d8b69788cb587ba203568b00acdd6d6fd550157851cb8932fb953ca412459b2c5f46aaff3e2c7de6c5bc5bac52e74663df72a7b952e5f923994f4c856ca52d

test:
  secret_key_base: c47c4d0fdf0b2c7f4214d4697c9ec68fe186d4fc4a8ad4b9e2f1f986e2a365e091123e0c9062751d12f1c95e76199adea52f3009286353f55b2cbf45013f8913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
